### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Tdaycode** [zuri-training/portfolia#2]
Implementation of landing page according to UI/UX

**Comment by Tdaycode** [comment]
Design Link https://www.figma.com/file/ZJvLM9kcGJBdL9qOESMsRa/Team-12-Portfolia-My-cms?node-id=158%3A107

**Comment by miftahuljna127** [comment]
> Implementation of landing page according to UI/UX

Sure, Thank you omotayo

**Comment by Estheronyi01** [comment]
Thank you omotayo
